//! Rust/Noir bridge integration tests (Phase 2).
//!
//! These tests load the compiled circuit artifacts from `circuits/target/`,
//! exercise the Rust-side helpers in `vertex-veil-noir`, and confirm that a
//! valid witness produces a solved ACIR instance. The `execute` path
//! validates every circuit constraint without requiring a proving backend,
//! which is sufficient to assert parity of the blake2s commitment scheme
//! between Rust and Noir.
//!
//! Plan coverage:
//!
//! - Happy Path: Rust witness generation matches the Noir circuit input
//!   schema; proof verification succeeds for a valid proof artifact
//!   generated by the local agent flow (interpreted as "execute succeeds"
//!   when the barretenberg feature is not enabled)
//! - Edge Cases: boundary price equality at the acceptance threshold
//!   verifies correctly; custom runtime capability labels still map
//!   correctly into the chosen circuit encoding
//! - Security: tampered public inputs invalidate an otherwise valid proof
//! - Data Leak: circuit integration errors redact private witness values

use std::path::PathBuf;

use vertex_veil_core::{
    CapabilityTag, NodeId, PrivateProviderIntent, PrivateRequesterIntent, RoundId, Secret,
};
use vertex_veil_noir::{
    CircuitArtifact, ProviderCircuit, ProviderWitness, RequesterCircuit, RequesterWitness,
};

fn repo_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("repo root from manifest dir")
        .to_path_buf()
}

fn requester_artifact_path() -> PathBuf {
    repo_root().join("circuits/target/vertex_veil_requester.json")
}

fn provider_artifact_path() -> PathBuf {
    repo_root().join("circuits/target/vertex_veil_provider.json")
}

fn load_requester() -> RequesterCircuit {
    let artifact = CircuitArtifact::from_path(requester_artifact_path())
        .expect("requester artifact present; run `nargo compile --workspace` in circuits/");
    RequesterCircuit::load(artifact).unwrap()
}

fn load_provider() -> ProviderCircuit {
    let artifact = CircuitArtifact::from_path(provider_artifact_path())
        .expect("provider artifact present; run `nargo compile --workspace` in circuits/");
    ProviderCircuit::load(artifact).unwrap()
}

fn req_intent(budget: u64, cap: &str) -> PrivateRequesterIntent {
    PrivateRequesterIntent {
        node_id: NodeId::from_bytes([0x11; 32]),
        required_capability: CapabilityTag::parse_shape(cap).unwrap(),
        budget_cents: Secret::new(budget),
        signing_secret_key: None,
    }
}

fn prov_intent(reservation: u64, claims: &[&str]) -> PrivateProviderIntent {
    PrivateProviderIntent {
        node_id: NodeId::from_bytes([0x22; 32]),
        capability_claims: claims
            .iter()
            .map(|c| CapabilityTag::parse_shape(c).unwrap())
            .collect(),
        reservation_cents: Secret::new(reservation),
        signing_secret_key: None,
    }
}

#[test]
fn noir_bridge_loads_requester_abi_in_expected_order() {
    let circuit = load_requester();
    // If ABI names diverge the load call itself errors, so reaching this
    // point already confirms the contract. Assert the bytecode is non-empty
    // for an extra smoke signal.
    assert!(!circuit.bytecode().is_empty());
}

#[test]
fn noir_bridge_loads_provider_abi_in_expected_order() {
    let circuit = load_provider();
    assert!(!circuit.bytecode().is_empty());
}

#[test]
fn noir_bridge_requester_executes_valid_witness() {
    let circuit = load_requester();
    let intent = req_intent(500, "GPU");
    let nonce = [0xa1; 32];
    let (public, _commit) =
        RequesterCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(0), 250)
            .unwrap();
    let witness = RequesterWitness {
        budget_cents: *intent.budget_cents.expose(),
        nonce,
    };
    circuit.execute(&public, &witness).expect("valid witness executes");
}

#[test]
fn noir_bridge_requester_boundary_threshold_equality_executes() {
    let circuit = load_requester();
    let intent = req_intent(100, "GPU");
    let nonce = [0xa1; 32];
    // Threshold equals budget; the circuit must accept (inclusive comparator).
    let (public, _commit) =
        RequesterCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(0), 100)
            .unwrap();
    let witness = RequesterWitness {
        budget_cents: *intent.budget_cents.expose(),
        nonce,
    };
    circuit.execute(&public, &witness).unwrap();
}

#[test]
fn noir_bridge_requester_tampered_round_fails_execute() {
    let circuit = load_requester();
    let intent = req_intent(500, "GPU");
    let nonce = [0xa1; 32];
    // Build commitment bound to round 0.
    let (mut public, _commit) =
        RequesterCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(0), 250)
            .unwrap();
    // Tamper the public round input.
    public.round = RoundId::new(1);
    let witness = RequesterWitness {
        budget_cents: *intent.budget_cents.expose(),
        nonce,
    };
    let err = circuit.execute(&public, &witness).unwrap_err();
    // Error message should not contain the (private) budget value.
    let msg = format!("{err}");
    assert!(!msg.contains("500"), "error leaked private budget: {msg}");
}

#[test]
fn noir_bridge_requester_tampered_commitment_fails_execute() {
    let circuit = load_requester();
    let intent = req_intent(500, "GPU");
    let nonce = [0xa1; 32];
    let (mut public, _commit) =
        RequesterCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(0), 250)
            .unwrap();
    // Flip a single byte of the published commitment hash.
    public.commitment_hash[0] ^= 0x01;
    let witness = RequesterWitness {
        budget_cents: *intent.budget_cents.expose(),
        nonce,
    };
    assert!(circuit.execute(&public, &witness).is_err());
}

#[test]
fn noir_bridge_requester_budget_below_threshold_fails_execute() {
    let circuit = load_requester();
    let intent = req_intent(99, "GPU");
    let nonce = [0xa1; 32];
    let (public, _commit) =
        RequesterCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(0), 100)
            .unwrap();
    let witness = RequesterWitness {
        budget_cents: *intent.budget_cents.expose(),
        nonce,
    };
    let err = circuit.execute(&public, &witness).unwrap_err();
    let msg = format!("{err}");
    // Budget 99 must not leak into the constraint-violation message.
    assert!(!msg.contains("99"), "error leaked private budget: {msg}");
}

#[test]
fn noir_bridge_requester_custom_capability_label_executes() {
    let circuit = load_requester();
    let intent = req_intent(500, "SPECIAL_ZONE");
    let nonce = [0xa1; 32];
    let (public, _commit) =
        RequesterCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(2), 500)
            .unwrap();
    let witness = RequesterWitness {
        budget_cents: *intent.budget_cents.expose(),
        nonce,
    };
    circuit.execute(&public, &witness).unwrap();
}

#[test]
fn noir_bridge_provider_executes_valid_witness() {
    let circuit = load_provider();
    let intent = prov_intent(200, &["GPU", "LLM"]);
    let nonce = [0xb2; 32];
    let (public, _commit) =
        ProviderCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(0), 300)
            .unwrap();
    let witness = ProviderWitness {
        reservation_cents: *intent.reservation_cents.expose(),
        nonce,
    };
    circuit.execute(&public, &witness).expect("valid witness executes");
}

#[test]
fn noir_bridge_provider_boundary_threshold_equality_executes() {
    let circuit = load_provider();
    let intent = prov_intent(200, &["GPU"]);
    let nonce = [0xb2; 32];
    let (public, _commit) =
        ProviderCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(0), 200)
            .unwrap();
    let witness = ProviderWitness {
        reservation_cents: *intent.reservation_cents.expose(),
        nonce,
    };
    circuit.execute(&public, &witness).unwrap();
}

#[test]
fn noir_bridge_provider_tampered_round_fails_execute() {
    let circuit = load_provider();
    let intent = prov_intent(150, &["GPU"]);
    let nonce = [0xb2; 32];
    let (mut public, _commit) =
        ProviderCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(0), 200)
            .unwrap();
    public.round = RoundId::new(5);
    let witness = ProviderWitness {
        reservation_cents: *intent.reservation_cents.expose(),
        nonce,
    };
    let err = circuit.execute(&public, &witness).unwrap_err();
    let msg = format!("{err}");
    assert!(!msg.contains("150"), "error leaked private reservation: {msg}");
}

#[test]
fn noir_bridge_provider_reservation_above_threshold_fails_execute() {
    let circuit = load_provider();
    let intent = prov_intent(301, &["GPU"]);
    let nonce = [0xb2; 32];
    let (public, _commit) =
        ProviderCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(0), 300)
            .unwrap();
    let witness = ProviderWitness {
        reservation_cents: *intent.reservation_cents.expose(),
        nonce,
    };
    assert!(circuit.execute(&public, &witness).is_err());
}

#[test]
fn noir_bridge_provider_multiple_claims_execute() {
    let circuit = load_provider();
    let intent = prov_intent(100, &["GPU", "CPU", "LLM", "ZK_DEV"]);
    let nonce = [0xb2; 32];
    let (public, _commit) =
        ProviderCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(1), 200)
            .unwrap();
    assert_eq!(public.n_claims, 4);
    let witness = ProviderWitness {
        reservation_cents: *intent.reservation_cents.expose(),
        nonce,
    };
    circuit.execute(&public, &witness).unwrap();
}

#[test]
fn noir_bridge_provider_custom_label_executes() {
    let circuit = load_provider();
    let intent = prov_intent(50, &["SPECIAL_ZONE"]);
    let nonce = [0xb2; 32];
    let (public, _commit) =
        ProviderCircuit::public_inputs_from_intent(&intent, &nonce, RoundId::new(0), 100)
            .unwrap();
    let witness = ProviderWitness {
        reservation_cents: *intent.reservation_cents.expose(),
        nonce,
    };
    circuit.execute(&public, &witness).unwrap();
}
